### ISSUE TITLE
Is it possible to use cloudflare tunnels?

### ISSUE THREAD

**Issue by Kuvwert** [bpbradley/matrix-turnify#1]
# Matrix Synapse + Matrix-Turnify Integration Issue

## Overview
I'm trying to integrate `matrix-turnify` into my Matrix Synapse deployment to offload TURN functionality to Cloudflare Calls. My setup runs Synapse and Postgres via Docker Compose on a Windows system, and I've added `matrix-turnify` as an additional service. My goal is to expose the TURN endpoint via a Cloudflare Tunnel using a dedicated subdomain.

Below is a summary of my setup, configuration changes, and troubleshooting steps taken.

---

### Docker Compose Configuration

My `docker-compose.yml` file includes Synapse, Postgres, and the `matrix-turnify` service.

```yaml
version: '3.7'

services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./data:/data
    environment: {}
    depends_on:
      postgres-synapse:
        condition: service_healthy

  postgres-synapse:
    container_name: postgres-synapse
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: <DB_PASSWORD>
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydbuser -d synapse -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  matrix-turnify:
    container_name: matrix-turnify
    image: ghcr.io/bpbradley/matrix-turnify:latest
    restart: always
    ports:
      - "4499:4499"
    environment:
      SYNAPSE_BASE_URL: http://synapse:8008/
      CF_TURN_TOKEN_ID: <CF_TURN_TOKEN_ID>
      CF_TURN_API_TOKEN: <CF_TURN_API_TOKEN>
      TURN_CREDENTIAL_TTL_SECONDS: 86400
      LOG_LEVEL: INFO
```

### Cloudflare Tunnel and DNS Configuration

My Cloudflare Tunnel (`cloudflared`) configuration file:

```yaml
tunnel: <YOUR_TUNNEL_ID>
credentials-file: /path/to/your/credentials.json

ingress:
  - hostname: turnify-matrix.mydomain.tld
    service: http://localhost:4499/
  - service: http_status:404
```

In Cloudflare DNS settings, I created a **CNAME** record for `turnify-matrix.mydomain.tld` pointing to the appropriate Cloudflare Tunnel target.

---

## Synapse TURN Configuration

I updated my `homeserver.yaml` to advertise the new TURN endpoint:

```yaml
server_name: "mydomain.tld"
pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    dsn: "postgres://mydbuser:<DB_PASSWORD>@postgres-synapse:5432/synapse?sslmode=disable"

logging:
  log_config: "/data/mydomain.tld.log.config"

media_store_path: /data/media_store

registration_shared_secret: "<REGISTRATION_SHARED_SECRET>"
enable_registration: true
enable_registration_captcha: false
enable_registration_without_verification: true

report_stats: false

macaroon_secret_key: "<MACAROON_SECRET_KEY>"
form_secret: "<FORM_SECRET>"
signing_key_path: "/data/mydomain.tld.signing.key"

trusted_key_servers:
  - server_name: "matrix.org"

turn_uris:
  - "turn:turnify-matrix.mydomain.tld?transport=udp"
  - "turn:turnify-matrix.mydomain.tld?transport=tcp"
  - "turns:turnify-matrix.mydomain.tld?transport=tcp"
```

This ensures that Matrix clients receive the TURN endpoints pointing to `turnify-matrix.mydomain.tld`.

---

### Direct Testing of TURN Endpoint
I verified the TURN endpoint using `curl`:

```sh
curl --header "Authorization: Bearer <YOUR_ACCESS_TOKEN>" -X GET \
     https://turnify-matrix.mydomain.tld/_matrix/client/v3/voip/turnServer
```

The response returned a valid JSON object containing fields such as:
- `username`
- `password`
- `ttl`
- List of `uris`

### Matrix Client Behavior
- TURN credentials are correctly generated (as verified via `curl`).
- The **Element** client does not successfully establish calls.
- **Jitsi calls work normally**.

### Diagnostic Steps Taken
1. Confirmed Cloudflare DNS and Tunnel configuration.
2. Verified that `matrix-turnify` returns valid TURN credentials.
3. Updated Synapse configuration to advertise the new TURN endpoint.

---

## Questions
1. **Is it possible to use a Cloudflare Tunnel in this manner** (exposing `matrix-turnify` via a dedicated subdomain like `turnify-matrix.mydomain.tld`) to serve TURN credentials for Matrix clients?
2. **Are there any known issues or additional configuration steps** required on the Cloudflare Tunnel side or within `matrix-turnify`/Synapse to make this approach work seamlessly with clients such as Element?

Any guidance or recommendations would be greatly appreciated.

**Thank you in advance for any insight you might have!**

**Comment by bpbradley** [comment]
Hey thanks for trying out the project! I'm at work at the moment but will take a look later this evening when I have some time to help you out.

My thought was that you would need a reverse proxy to do this, but you SHOULD be able to use cloudflare tunnels as that reverse proxy with some routing rules if I recall correctly. Let me play around with it tonight and get back to you.

**Comment by bpbradley** [comment]
Basically real quick though, at a glance it seems you are trying to configure the turn server with its own domain, and then configure your synapse server to use that.

turnify is actually not designed that way (as sybapse homeserver is actually just not compatible with how cloudflare calls works). I started by trying to implement it the way you are expecting, but soon realized it was not going to work. 

So instead, the idea is to intercept your matrix client requests for turn server credentials, and return your cloudflare calls credentials in the same format that your matrix server would.

So basically, you want turnify listening on `matrix.domain.tld` but _only_ at the /voip/turnServer route (this way, matrix gets all traffic except for the specific requests from clients for turn server credentials). 

So essentially, your matrix home server does not even need to be configured for use with turn.

**Comment by bpbradley** [comment]
> # Matrix Synapse + Matrix-Turnify Integration Issue
> ## Overview
> I'm trying to integrate `matrix-turnify` into my Matrix Synapse deployment to offload TURN functionality to Cloudflare Calls. My setup runs Synapse and Postgres via Docker Compose on a Windows system, and I've added `matrix-turnify` as an additional service. My goal is to expose the TURN endpoint via a Cloudflare Tunnel using a dedicated subdomain.
> 
> Below is a summary of my setup, configuration changes, and troubleshooting steps taken.
> 
> ## My Setup
> ### Docker Compose Configuration
> My `docker-compose.yml` file includes Synapse, Postgres, and the `matrix-turnify` service.
> 
> version: '3.7'
> 
> services:
>   synapse:
>     container_name: synapse
>     image: matrixdotorg/synapse:latest
>     restart: always
>     ports:
>       - "8008:8008"
>     volumes:
>       - ./data:/data
>     environment: {}
>     depends_on:
>       postgres-synapse:
>         condition: service_healthy
> 
>   postgres-synapse:
>     container_name: postgres-synapse
>     image: postgres:13
>     restart: unless-stopped
>     environment:
>       POSTGRES_USER: mydbuser
>       POSTGRES_PASSWORD: <DB_PASSWORD>
>       POSTGRES_DB: synapse
>       POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
>     volumes:
>       - ./pgdata:/var/lib/postgresql/data
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U mydbuser -d synapse -h localhost"]
>       interval: 10s
>       timeout: 5s
>       retries: 5
> 
>   matrix-turnify:
>     container_name: matrix-turnify
>     image: ghcr.io/bpbradley/matrix-turnify:latest
>     restart: always
>     ports:
>       - "4499:4499"
>     environment:
>       SYNAPSE_BASE_URL: http://synapse:8008/
>       CF_TURN_TOKEN_ID: <CF_TURN_TOKEN_ID>
>       CF_TURN_API_TOKEN: <CF_TURN_API_TOKEN>
>       TURN_CREDENTIAL_TTL_SECONDS: 86400
>       LOG_LEVEL: INFO
> ### Cloudflare Tunnel and DNS Configuration
> My Cloudflare Tunnel (`cloudflared`) configuration file:
> 
> tunnel: <YOUR_TUNNEL_ID>
> credentials-file: /path/to/your/credentials.json
> 
> ingress:
>   - hostname: turnify-matrix.mydomain.tld
>     service: http://localhost:4499/
>   - service: http_status:404
> In Cloudflare DNS settings, I created a **CNAME** record for `turnify-matrix.mydomain.tld` pointing to the appropriate Cloudflare Tunnel target.
> 
> ## Synapse TURN Configuration
> I updated my `homeserver.yaml` to advertise the new TURN endpoint:
> 
> server_name: "mydomain.tld"
> pid_file: /data/homeserver.pid
> 
> listeners:
>   - port: 8008
>     tls: false
>     type: http
>     x_forwarded: true
>     resources:
>       - names: [client, federation]
>         compress: false
> 
> database:
>   name: psycopg2
>   args:
>     dsn: "postgres://mydbuser:<DB_PASSWORD>@postgres-synapse:5432/synapse?sslmode=disable"
> 
> logging:
>   log_config: "/data/mydomain.tld.log.config"
> 
> media_store_path: /data/media_store
> 
> registration_shared_secret: "<REGISTRATION_SHARED_SECRET>"
> enable_registration: true
> enable_registration_captcha: false
> enable_registration_without_verification: true
> 
> report_stats: false
> 
> macaroon_secret_key: "<MACAROON_SECRET_KEY>"
> form_secret: "<FORM_SECRET>"
> signing_key_path: "/data/mydomain.tld.signing.key"
> 
> trusted_key_servers:
>   - server_name: "matrix.org"
> 
> turn_uris:
>   - "turn:turnify-matrix.mydomain.tld?transport=udp"
>   - "turn:turnify-matrix.mydomain.tld?transport=tcp"
>   - "turns:turnify-matrix.mydomain.tld?transport=tcp"
> This ensures that Matrix clients receive the TURN endpoints pointing to `turnify-matrix.mydomain.tld`.
> 
> ## Troubleshooting and Observations
> ### Direct Testing of TURN Endpoint
> I verified the TURN endpoint using `curl`:
> 
> curl --header "Authorization: Bearer <YOUR_ACCESS_TOKEN>" -X GET \
>      https://turnify-matrix.mydomain.tld/_matrix/client/v3/voip/turnServer
> The response returned a valid JSON object containing fields such as:
> 
> * `username`
> * `password`
> * `ttl`
> * List of `uris`
> 
> ### Matrix Client Behavior
> * TURN credentials are correctly generated (as verified via `curl`).
> * The **Element** client does not successfully establish calls.
> * **Jitsi calls work normally**.
> 
> ### Diagnostic Steps Taken
> 1. Confirmed Cloudflare DNS and Tunnel configuration.
> 2. Verified that `matrix-turnify` returns valid TURN credentials.
> 3. Updated Synapse configuration to advertise the new TURN endpoint.
> 
> ## Questions
> 1. **Is it possible to use a Cloudflare Tunnel in this manner** (exposing `matrix-turnify` via a dedicated subdomain like `turnify-matrix.mydomain.tld`) to serve TURN credentials for Matrix clients?
> 2. **Are there any known issues or additional configuration steps** required on the Cloudflare Tunnel side or within `matrix-turnify`/Synapse to make this approach work seamlessly with clients such as Element?
> 
> Any guidance or recommendations would be greatly appreciated.
> 
> **Thank you in advance for any insight you might have!**

Okay so being in front of my computer for a moment, to summarize what I was saying in my previous comment, what you really want to be doing is something like this (I don't know if it will work exactly like this with cloudflared, but this is the concept)

```
tunnel: <YOUR_TUNNEL_ID>
credentials-file: /path/to/your/credentials.json

ingress:
  - hostname: matrix.mydomain.tld
    service: http://localhost:8008/
  - hostname: matrix.mydomain.tld
    path: "^.*/voip/turnServer$"
    service: https://localhost:8001
  - service: http_status:404
```

Basically, the way this works is that whenever you make a request to `matrix.mydomain.tld/some/random/path` you will be routed to your matrix homeserver, as expected. But when you make a request to a path that matches `^.*/voip/turnServer$` like `matrix.mydomain.tld/some/client/request/to/voip/turnServer`, _then_ turnify will handle that request, and that kind of request only. (typically this would be something like `^/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$` to be more precise)

Once turnify gets this request, it first forwards the request directly to your actual synapse server (which is what it needs to know the synapse url), and makes sure the user is authenticated. Then only authenticated requests for that resource will be returned to the client. turnify formats the response exactly the same way that synapse does, so the client just sees credentials in the form it expects them, and is able to connect with them.

You can check the Requirements section of the README for more details on how it works, but hopefully this will get you in the right direction.

**Comment by Kuvwert** [comment]
Thanks for the feedback! Following your guidance, I've attempted to set this up with Cloudflare tunnels as the reverse proxy. Here's what I've done:

1. Set up two ingress rules in Cloudflare Zero Trust:
```yaml
hostname: thematrix.epiq.cc
path: "^/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$"
service: http://localhost:4499

hostname: thematrix.epiq.cc
service: http://localhost:8008
```

I changed the path pattern from `^.*/voip/turnServer$` to `^/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$` to capture all possible API version paths that Matrix clients might use when requesting TURN credentials.

2. Removed TURN configuration from my `homeserver.yaml` as suggested

3. Using matrix-turnify with the following Docker configuration:
```yaml 
matrix-turnify:
  image: ghcr.io/bpbradley/matrix-turnify:latest
  container_name: matrix-turnify
  restart: always
  ports:
    - "4499:4499"
  environment:
    - SYNAPSE_BASE_URL=http://synapse:8008
    - CF_TURN_TOKEN_ID=[redacted]
    - CF_TURN_API_TOKEN=[redacted]
    - TURN_CREDENTIAL_TTL_SECONDS=86400
    - LOG_LEVEL=INFO
```

The turnify API is working correctly - I can verify this by checking the logs and testing the endpoint:
```bash
$ curl -H "Authorization: Bearer [token]" https://thematrix.epiq.cc/_matrix/client/v3/voip/turnServer
{
  "username": "...",
  "password": "...",
  "ttl": 86400,
  "uris": [
    "stun:stun.cloudflare.com:3478",
    "turn:turn.cloudflare.com:3478?transport=udp",
    "turn:turn.cloudflare.com:3478?transport=tcp",
    "turns:turn.cloudflare.com:5349?transport=tcp"
  ]
}
```

The turnify logs show successful 200 responses when initiating calls. However, calls get stuck on "connecting" and never establish a media connection. Would appreciate any suggestions on what else to check or configure. Is there something Im supposed to do the the element client to get this to work?
